# Autogenerated by LiteX / git: 04f6b17d
set -e
yosys -l ulx3s.rpt ulx3s.ys
nextpnr-ecp5 --json ulx3s.json --lpf ulx3s.lpf --textcfg ulx3s.config      --45k --package CABGA381 --speed 6 --timing-allow-fail  --seed 1
ecppack ulx3s.config --svf ulx3s.svf --bit ulx3s.bit --bootaddr 0  --compress
